### PR TITLE
Add zk-spaced to list of related projects

### PR DESCRIPTION
**Pull request by matze**
Also take the opportunity to unify the dashes.

### CODE REVIEW

**Review by mickael-menu — APPROVED** [review]
Thank you, that looks like an interesting project!

I thought of adding SRS features in `zk` directly, but as an external plugin it makes much sense. Let me know if something could be changed in `zk` to help you build `zk-spaced`.

**Comment by matze** [comment]
> Let me know if something could be changed in zk to help you build zk-spaced.

I think negotiating the output format without having the user do it would be nice. But I don't think it's worth making the whole interaction more complex. So, all good :-)

**Comment by mickael-menu** [comment]
Having `zk-*` binaries implicitly available as `zk` subcommands could be a minimal way to support external plugins seamlessly. For example your hypothetical `zk-review` binary would call `zk` directly with the expected arguments (`--format json`) and it would be available to the user as `zk review` without modifying their config.

I think it's pretty standard, see for example `git-lfs`.

**Comment by matze** [comment]
Sounds like a reasonable approach, yes.

**Pull request merged**
