### PR TITLE
Add `notebook` configuration to set default notebook path

### PR DESCRIPTION
**Pull request by lsvmello**
As mentioned on https://github.com/mickael-menu/zk/issues/300.

This is the proposed solution to add the default notebook path on the `config.toml`.

### CODE REVIEW

**Review by mickael-menu — COMMENTED** [review]
I'm uncomfortable authorizing a `notebook.dir` config key in all `config.toml` files, because it wouldn't make sense (and could be incorrect) in the `config.toml` embedded inside a notebook (`.zk/config.toml`).

Would you mind updating your PR to only parse such key in the global config file? Maybe outputting an error if `notebook.dir` is set inside a "local" `config.toml`.

**Comment by lsvmello** [comment]
Hey @mickael-menu is there anything else left for me to do here?

**Comment by mickael-menu** [comment]
Sorry, I didn't receive any GitHub notification. I'll take a look.

**Review by mickael-menu — APPROVED** [review]
Looking good, thank you 👍

**Pull request merged**
